In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)

# Load the cleaned dataset
df = pd.read_csv("CleanData/himalayan_climbers_clean.csv")

print("Dataset shape:", df.shape)
df.head()

Dataset shape: (73007, 15)

,year,season,peak_name,peak_height_m,age,sex,citizenship,expedition_role,hired,solo,oxygen_used,expedition_size,peak_hist_fatality_rate,peak_hist_climbs,died
0,2014,Autumn,Manaslu,8163.0,30.0,M,Nepal,H-A Worker,1,0,1,20,0.023004,3043,0
1,1999,Autumn,Other,7227.0,29.0,M,Spain,Climber,0,0,0,5,0.048507,268,0
2,1997,Autumn,Ama Dablam,6814.0,27.0,M,USA,Climber,0,0,0,8,0.007488,1202,0
3,1996,Autumn,Manaslu,8163.0,25.0,M,Italy,Climber,0,0,0,10,0.042986,884,0
4,2003,Spring,Everest,8850.0,37.0,M,Other,Climber,0,0,0,17,0.019446,7405,0

In [5]:
#Basic information  about the dataset
print("Dataset shape:", df.shape)
print("\nColumn names:")
print(df.columns.tolist())
print("\nData types:")
print("df.dtypes")
print("\nMissing values:")
print(df.isnull().sum())

Dataset shape: (73007, 15)

Column names:
['year', 'season', 'peak_name', 'peak_height_m', 'age', 'sex', 'citizenship', 'expedition_role', 'hired', 'solo', 'oxygen_used', 'expedition_size', 'peak_hist_fatality_rate', 'peak_hist_climbs', 'died']

Data types:
df.dtypes

Missing values:
year                       0
season                     0
peak_name                  0
peak_height_m              0
age                        0
sex                        0
citizenship                0
expedition_role            0
hired                      0
solo                       0
oxygen_used                0
expedition_size            0
peak_hist_fatality_rate    0
peak_hist_climbs           0
died                       0
dtype: int64

In [6]:
#Check for duplicates rows
print("Number of duplicates rows:",df.duplicated().sum())

Number of duplicates rows: 6013

In [7]:
#Summary Statisrics for numerical columns
df.describe()

,year,peak_height_m,age,hired,solo,oxygen_used,expedition_size,peak_hist_fatality_rate,peak_hist_climbs,died
count,73007.000000,73007.000000,73007.000000,73007.000000,73007.000000,73007.000000,73007.000000,73007.000000,73007.000000,73007.000000
mean,2001.001616,7936.752092,37.335721,0.191488,0.001589,0.243401,13.591560,0.017494,4217.241402,0.012725
std,14.126299,836.667068,10.394613,0.393475,0.039829,0.429138,11.556458,0.015512,5281.387862,0.112085
min,1905.000000,5407.000000,7.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
25%,1992.000000,7138.000000,29.000000,0.000000,0.000000,0.000000,6.000000,0.006761,308.000000,0.000000
50%,2004.000000,8167.000000,36.000000,0.000000,0.000000,0.000000,11.000000,0.014231,1789.000000,0.000000
75%,2012.000000,8850.000000,44.000000,0.000000,0.000000,0.000000,17.000000,0.022959,6274.000000,0.000000
max,2019.000000,8850.000000,85.000000,1.000000,1.000000,1.000000,99.000000,0.217391,19955.000000,1.000000

In [8]:
#Number of unique value in each column
print("Unique values in each column:")
print(df.nunique().sort_values())

Unique values in each column:
sex                          2
hired                        2
solo                         2
oxygen_used                  2
died                         2
season                       4
expedition_role              4
peak_name                   16
citizenship                 16
expedition_size             68
age                         74
year                        90
peak_height_m              353
peak_hist_climbs           676
peak_hist_fatality_rate    861
dtype: int64

In [9]:
#Check value of categorical columns
categoricals_cols = df.select_dtypes(include="object").columns
for col in categoricals_cols:
    print(f"\n---{col}---")
print(df[col].value_counts().head(10))

---season---

---peak_name---

---sex---

---citizenship---

---expedition_role---
expedition_role
Climber       43614
H-A Worker    13793
Leader        11457
Other          4143
Name: count, dtype: int64